-- DROP TABLE hits CASCADE;

CREATE TABLE IF NOT EXISTS hits (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     app VARCHAR(20) NOT NULL,
                                     uri VARCHAR(30) NOT NULL,
                                     ip VARCHAR(30) NOT NULL,
                                     timestamp TIMESTAMP NOT NULL ,
                                     CONSTRAINT pk_hit PRIMARY KEY (id)
);