-- DROP TABLE hits CASCADE;

CREATE TABLE IF NOT EXISTS hits (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     app VARCHAR(50),
                                     uri VARCHAR(30),
                                     ip VARCHAR(30),
                                     timestamp TIMESTAMP,
                                     CONSTRAINT pk_hit PRIMARY KEY (id)
);